version: '3'
services:
  nginx:
    image: josephpatricksoloman/nginx-custom:latest
    ports:
      - "8080:80"
    volumes:
      - ./html:/var/opt/nginx
    networks:
      - webnet

networks:
  webnet:
